export const dataBase = {
  Минск: {
    1: {
      address: 'Притыцкого 100',
      phones: {
        1: '+37529 854 14 849',
        2: '+37544 978 54 875',
      },
      menuList: ['Пицца', 'Суши', 'Сеты', 'Напитки', 'Акции'],
      products: {
        Пицца: {
          imgName: 'pizza.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Суши: {
          imgName: 'sushi.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Сеты: {
          imgName: 'set.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Напитки: {
          imgName: 'drinks.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Акции: {
          imgName: 'sale.png',
        },
      },
    },

    2: {
      address: 'Крапоткина 10',
      phones: {
        1: '+37529 854 00 000',
        2: '+37544 978 04 005',
      },
      menuList: ['Пицца', 'Салаты', 'Напитки', 'Акции'],
      products: {
        Пицца: {
          imgName: 'pizza.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Салаты: {
          imgName: 'salads.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Напитки: {
          imgName: 'drinks.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Акции: {
          imgName: 'sale.png',
        },
      },
    },
  },

  Брест: {
    1: {
      address: 'Московская 106',
      phones: {
        1: '+37529 875 15 849',
        2: '+37544 900 44 888',
      },
      menuList: ['Суши', 'Сеты', 'Напитки', 'Акции'],
      products: {
        Суши: {
          imgName: 'sushi.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Сеты: {
          imgName: 'set.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Напитки: {
          imgName: 'drinks.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Акции: {
          imgName: 'sale.png',
        },
      },
    },
  },
  Гродно: {
    1: {
      address: 'Элизы Ожешко 1',
      phones: {
        1: '+37529 353 17 353',
        2: '+37533 458 68 800',
      },
      menuList: ['Пицца', 'Салаты', 'Напитки', 'Акции'],
      products: {
        Пицца: {
          imgName: 'pizza.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Салаты: {
          imgName: 'salads.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Напитки: {
          imgName: 'drinks.png',
          id: {
            1: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
            2: {
              name: 'Сет "4 Филадельфии"',
              imgName: './img/setImages/set4.png',
              description: '1100 грамм 32 кусочек',
              amountOfbits: '32',
              weight: '',
              price: '15',
              currency: 'BYN',
              count: 100,
              action: {
                true: 'true',
                newPrice: '',
              },
              popular: true,
            },
          },
        },
        Акции: {
          imgName: 'sale.png',
        },
      },
    },
  },
};
