export const productSpecificationData = {
  wok1: {
    name: 'Ясай Яки Сомен (грибы)',
    imgName: 'WOK1.jpg',
    description: '410 грамм',
    ingridients: 'Фасоль стручковая, лук красный, морковь, перец болгарский, шампиньоны, грибы шиитаки, цукини, масло чесночное, лапша  яичная, бульон вок, соус вок, томат черри, кунжут белый, ростки соевые, микрозелень.',
    amountOfbits: '',
    weight: '410',
    price: '14.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: true,
  },
  wok2: {
    name: 'Тори Яки Тяхан (курица)',
    imgName: 'WOK2.jpg',
    description: '431 грамм',
    ingridients: 'Мякоть бедра цыплёнка, цукини, лук красный, морковь, перец болгарский, масло чесночное, горошек зелёный, рис, бульон вок, соус вок, томат черри, соевые ростки, микрозелень.',
    amountOfbits: '',
    weight: '431',
    price: '15.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  wok3: {
    name: 'Тори Яки Удон (курица)',
    imgName: 'WOK3.jpg',
    description: '414 грамм',
    ingridients: 'Мякоть бедра цыплёнка, цукини, лук красный, морковь, перец болгарский, фасоль стручковая, масло чесночное, лапша пшеничная, бульон вок, соус карри, томат черри, кунжут белый, ростки соевые, микрозелень',
    amountOfbits: '',
    weight: '414',
    price: '15.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  wok4: {
    name: 'Батакон Яки Тяхан',
    imgName: 'WOK4.jpg',
    description: '445 грамм',
    ingridients: 'Бекон, цукини, лук красный, морковь, перец свежий, масло чесночное, горошек зелёный, рис, бульон вок, соус соевый, кунжутное масло, яйцо куриное, ростки соевые, томат черри, микрозелень.',
    amountOfbits: '',
    weight: '445',
    price: '16.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  wok5: {
    name: 'Сифудо Яки Тяхан',
    imgName: 'WOK5.jpg',
    description: '415 грамм',
    ingridients: 'Фасоль стручковая, лук красный, морковь, перец болгарский, шампиньоны, грибы шиитаки, цукини, масло чесночное, лапша  яичная, бульон вок, соус вок, томат черри, кунжут белый, ростки соевые, микрозелень.',
    amountOfbits: '',
    weight: '415',
    price: '21.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  wok6: {
    name: 'Эби тори Яки Удон',
    imgName: 'WOK6.jpg',
    description: '419 грамм',
    ingridients: 'Бекон, цукини, лук красный, морковь, перец свежий, масло чесночное, горошек зелёный, рис, бульон вок, соус соевый, кунжутное масло, яйцо куриное, ростки соевые, томат черри, микрозелень.',
    amountOfbits: '',
    weight: '419',
    price: '21.99',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '15.99',
    popular: false,
    new: false,
  },
  wok7: {
    name: 'Бифу Яки',
    imgName: 'WOK7.jpg',
    description: '410 грамм',
    ingridients: 'Вырезка говяжья, цукини, лук красный, морковь, перец болгарский, фасоль стручковая, масло чесночное, лапша гречневая, бульон вок, соус вок, томат черри, кунжут белый, ростки соевые, микрозелень.',
    amountOfbits: '',
    weight: '410',
    price: '21.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  wok8: {
    name: 'Ясай Сомен (говядина)',
    imgName: 'WOK8.jpg',
    description: '423 грамм',
    ingridients: 'Вырезка говяжья, цукини, лук красный, морковь, перец болгарский, фасоль стручковая, масло чесночное, лапша гречневая, бульон вок, соус вок, томат черри, кунжут белый, ростки соевые, микрозелень.',
    amountOfbits: '',
    weight: '423',
    price: '21.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  wok9: {
    name: 'Сифудо Яки Шахэфэнь',
    imgName: 'WOK9.jpg',
    description: '445 грамм',
    ingridients: 'Креветка, кальмар, мидии, осьминог, вино белое, цукини, лук красный, морковь, масло чесночное, перец болгарский, фасоль стручковая, лапша рисовая, бульон вок, соус терияки, томат черри, ростки соевые, кунжут белый, микрозелень.',
    amountOfbits: '',
    weight: '445',
    price: '24.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi1: {
    name: 'Каппа Пира маки',
    imgName: 'sushi1.jpg',
    description: '219 грамм 8шт.',
    ingridients: 'Лосось жареный в соусе Терияки, сливочный сыр, огурец, соус Терияки, кунжут белый',
    amountOfbits: '8',
    weight: '219',
    price: '11.90',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '7.99',
    popular: true,
    new: false,
  },
  sushi2: {
    name: 'Бекон Пира маки',
    imgName: 'sushi2.jpg',
    description: '231 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '231',
    price: '15.50',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '9.99',

    popular: false,
    new: false,
  },
  sushi3: {
    name: 'Ширу маки',
    imgName: 'sushi3.jpg',
    description: '259 грамм 8шт.',
    ingridients: 'Морской окунь, яблоко, салат Айсберг, чёрный кунжут, сыр сливочный, перец свежий, соус Чили сладкий',
    amountOfbits: '8',
    weight: '259',
    price: '9.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  sushi4: {
    name: 'Мидори маки',
    imgName: 'sushi4.jpg',
    description: '224 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '224',
    price: '8.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  sushi5: {
    name: 'Сингапур маки',
    imgName: 'sushi5.jpg',
    description: '259 грамм 8шт.',
    ingridients: 'Морской окунь, яблоко, салат Айсберг, чёрный кунжут, сыр сливочный, перец свежий, соус Чили сладкий',
    amountOfbits: '8',
    weight: '259',
    price: '13.90',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '9.99',

    popular: true,
    new: false,
  },
  sushi6: {
    name: 'Тори Чизу маки',
    imgName: 'sushi6.jpg',
    description: '240 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '240',
    price: '15.50',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '9.99',

    popular: false,
    new: true,
  },
  sushi7: {
    name: 'Флорида маки',
    imgName: 'sushi7.jpg',
    description: '222 грамм 8шт.',
    ingridients: 'Сурими, тобико, мидии, сливочный сыр, салат Айсберг, лук зеленый, крем Васаби',
    amountOfbits: '8',
    weight: '222',
    price: '13.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi8: {
    name: 'Шиитаке маки',
    imgName: 'sushi8.jpg',
    description: '199 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '199',
    price: '9.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  sushi9: {
    name: 'Пинку маки',
    imgName: 'sushi9.jpg',
    description: '210 грамм 8шт.',
    ingridients: 'Сурими, тобико, мидии, сливочный сыр, салат Айсберг, лук зеленый, крем Васаби',
    amountOfbits: '8',
    weight: '210',
    price: '9.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  sushi10: {
    name: 'Сурими муракай маки',
    imgName: 'sushi10.jpg',
    description: '222 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '222',
    price: '9.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  sushi11: {
    name: 'Тамаго маки',
    imgName: 'sushi11.jpg',
    description: '237 грамм 8шт.',
    ingridients: 'Сурими, тобико, мидии, сливочный сыр, салат Айсберг, лук зеленый, крем Васаби',
    amountOfbits: '8',
    weight: '237',
    price: '10.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi12: {
    name: 'Батакон маки',
    imgName: 'sushi12.jpg',
    description: '252 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '252',
    price: '11.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  sushi13: {
    name: 'Ямато маки',
    imgName: 'sushi13.jpg',
    description: '219 грамм 8шт.',
    ingridients: 'Сурими, тобико, мидии, сливочный сыр, салат Айсберг, лук зеленый, крем Васаби',
    amountOfbits: '8',
    weight: '219',
    price: '15.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi14: {
    name: 'Эдо маки',
    imgName: 'sushi14.jpg',
    description: '214 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '214',
    price: '13.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  sushi15: {
    name: 'Эби Чеддер маки',
    imgName: 'sushi15.jpg',
    description: '219 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '219',
    price: '15.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi16: {
    name: 'Эби Филадельфия маки',
    imgName: 'sushi16.jpg',
    description: '244 грамм 8шт.',
    ingridients: 'Сурими, тобико, мидии, сливочный сыр, салат Айсберг, лук зеленый, крем Васаби',
    amountOfbits: '8',
    weight: '244',
    price: '18.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  sushi17: {
    name: 'Эби Калифорния маки',
    imgName: 'sushi17.jpg',
    description: '204 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '204',
    price: '19.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  sushi18: {
    name: 'Чили Изумитай маки',
    imgName: 'sushi18.jpg',
    description: '240 грамм 8шт.',
    ingridients: 'Сурими, тобико, мидии, сливочный сыр, салат Айсберг, лук зеленый, крем Васаби',
    amountOfbits: '8',
    weight: '240',
    price: '15.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  sushi19: {
    name: 'Филадельфия Фреш маки',
    imgName: 'sushi19.jpg',
    description: '253 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '253',
    price: '19.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi20: {
    name: 'Филадельфия маки',
    imgName: 'sushi20.jpg',
    description: '282 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '282',
    price: '22.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi21: {
    name: 'Филадельфия Кунсей маки',
    imgName: 'sushi21.jpg',
    description: '262 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '262',
    price: '20.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi22: {
    name: 'Филадельфия Авокадо маки',
    imgName: 'sushi22.jpg',
    description: '285 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '285',
    price: '22.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  sushi23: {
    name: 'Тамагу Кунсей маки',
    imgName: 'sushi23.jpg',
    description: '259 грамм 8шт.',
    ingridients: 'Опаленный бекон, лосось жаренный в соусе Терияки, сливочный сыр, соус Терияки',
    amountOfbits: '8',
    weight: '259',
    price: '14.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  set1: {
    name: 'Окинава сет',
    imgName: 'set1.jpg',
    description: '900 грамм 32шт.',
    ingridients: 'Мияги маки, Флорида маки, Эдо маки, Пинку маки',
    amountOfbits: '32',
    weight: '884',
    price: '35.10',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  set2: {
    name: 'Осака сет',
    imgName: 'set2.jpg',
    description: '864 грамм 32шт.',
    ingridients: 'Эби Чеддер маки, Эдо маки, Акита маки, Асахи маки',
    amountOfbits: '32',
    weight: '864',
    price: '49.90',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '39.90',
    popular: true,
    new: false,
  },
  set3: {
    name: 'Кудасай сет ',
    imgName: 'set3.jpg',
    description: '864 грамм 32шт.',
    ingridients: 'Филадельфия Фреш маки, Пинку маки, Фреш маки, Ямато маки',
    amountOfbits: '32',
    weight: '864',
    price: '44.10',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '34.90',
    popular: true,
    new: false,
  },
  set4: {
    name: 'Ля Мур сет',
    imgName: 'set4.jpg',
    description: '997 грамм 32шт.',
    ingridients: 'Филадельфия фреш маки, Бали маки, Микс Филадельфия маки, Флорида маки',
    amountOfbits: '32',
    weight: '997',
    price: '55.10',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '49.90',
    popular: true,
    new: false,
  },
  set5: {
    name: 'Сяке сет',
    imgName: 'set5.jpg',
    description: '846 грамм 40шт.',
    ingridients: 'Пять ролов с лососем в сочетании с авокадо, огурцом, луком  и сливочным сыром.',
    amountOfbits: '40',
    weight: '846',
    price: '45.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',

    popular: false,
    new: true,
  },
  set6: {
    name: 'Бонсай сет',
    imgName: 'set6.jpg',
    description: '929 грамм 32шт.',
    ingridients: 'Филадельфия Фреш маки, Флорида маки, Эдо маки, Тори Чизу маки',
    amountOfbits: '32',
    weight: '929',
    price: '43.80',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  set7: {
    name: 'Кабуки сет',
    imgName: 'set7.jpg',
    description: '903 грамм 32шт.',
    ingridients: 'Сингу Маки, Кьюри маки, Кацуо-буши маки, Татаки Сяке Кунсей маки',
    amountOfbits: '32',
    weight: '903',
    price: '59.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: true,
  },
  set8: {
    name: 'Хит сет',
    imgName: 'set8.jpg',
    description: '1030 грамм 32шт.',
    ingridients: 'Филадельфия Фреш маки, Эби Калифонрния маки, Ямато маки, Флорида маки',
    amountOfbits: '32',
    weight: '1030',
    price: '44.10',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: true,
  },
  set9: {
    name: 'Филадельфия сан сет',
    imgName: 'set9.jpg',
    description: '1085 грамм 32шт.',
    ingridients: 'Филадельфия маки, Филадельфия Фреш маки, Филадельфия Авокадо маки, Кунсей Филадельфия маки',
    amountOfbits: '32',
    weight: '1085',
    price: '44.10',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  set10: {
    name: 'Сушимания сет',
    imgName: 'set10.jpg',
    description: '1200 грамм 40шт.',
    ingridients: 'Мияги маки, Флорида маки, Эдо маки, Пинку маки',
    amountOfbits: '40',
    weight: '1200',
    price: '70.99',
    currency: 'BYN',
    count: 100,
    sale: true,
    newPrice: '65.90',
    popular: false,
    new: false,
  },
  set11: {
    name: 'Ахимса сет',
    imgName: 'set11.jpg',
    description: '678 грамм 32шт.',
    ingridients: 'Мияги маки, Флорида маки, Эдо маки, Пинку маки',
    amountOfbits: '32',
    weight: '678',
    price: '37.10',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  salad1: {
    name: 'Киото сарада',
    imgName: 'salad1.jpg',
    description: '158 грамм',
    ingridients: 'Мясо на выбор, микс салатов, огурец, томаты черри, сырные шарики, заправка Киото',
    amountOfbits: '',
    weight: '158',
    price: '14.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  salad2: {
    name: 'Цезарь',
    imgName: 'salad2.jpg',
    description: '170 грамм',
    ingridients: 'Микс салатов, томаты Черри, гренки из багета, пармезан, соус Цезарь',
    amountOfbits: '',
    weight: '170',
    price: '15.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: true,
    new: false,
  },
  salad3: {
    name: 'Тори Киноко',
    imgName: 'salad3.jpg',
    description: '320 грамм',
    ingridients: 'Микс салатов, огурец, морковь, курица, томаты Черри, редис, грибы, чакин, пряная заправка, соус Спайси',
    amountOfbits: '',
    weight: '320',
    price: '15.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  salad4: {
    name: 'Батакон Яки Тяхан',
    imgName: 'salad4.jpg',
    description: '145 грамм',
    ingridients: 'Маринованные морские водоросли, кунжут черный',
    amountOfbits: '',
    weight: '145',
    price: '9.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink1: {
    name: 'Вода "Святой источник"',
    imgName: 'drink1.jpg',
    description: '500 мл',
    ingridients: 'Питьевая вода',
    amountOfbits: '',
    weight: '',
    price: '1.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink2: {
    name: 'Боржоми',
    imgName: 'drink2.jpg',
    description: '330 мл',
    ingridients: 'Минеральная вода вулканического происхождения',
    amountOfbits: '',
    weight: '',
    price: '5.00',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink3: {
    name: 'Бонаква',
    imgName: 'drink3.jpg',
    description: '500 мл',
    ingridients: 'Среднегазированная питьевая вода ',
    amountOfbits: '',
    weight: '',
    price: '1.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink4: {
    name: 'Кока-кола',
    imgName: 'drink4.jpg',
    description: '500 мл',
    ingridients: 'Кока-кола',
    amountOfbits: '',
    weight: '',
    price: '3.99',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink5: {
    name: 'Fanta',
    imgName: 'drink5.jpg',
    description: '500 мл',
    ingridients: 'Fanta',
    amountOfbits: '',
    weight: '',
    price: '3.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink6: {
    name: 'Sprite',
    imgName: 'drink6.jpg',
    description: '500 мл',
    ingridients: 'Sprite',
    amountOfbits: '',
    weight: '',
    price: '3.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink7: {
    name: 'Сок Rich вишня (ПЭТ)',
    imgName: 'drink7.jpg',
    description: '330 мл',
    ingridients: 'Сок вишневый',
    amountOfbits: '',
    weight: '',
    price: '2.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
  drink8: {
    name: 'Сок Rich апельсин',
    imgName: 'drink8.jpg',
    description: '1000 мл',
    ingridients: 'Сок апельсиновый',
    amountOfbits: '',
    weight: '',
    price: '5.90',
    currency: 'BYN',
    count: 100,
    sale: false,
    newPrice: '',
    popular: false,
    new: false,
  },
};
